import type { ScenarioSeed } from "../types"

const SCENARIOS: ScenarioSeed[] = [
  {
    id: "barber-executive-cut",
    title: "Barbearia: corte executivo com desvios gerais",
    domain: "barbearia",
    businessVertical: "appointment",
    persona: "Cliente indeciso, quer parecer mais profissional sem mudar demais.",
    initialGoal: "Escolher e marcar um corte masculino mais executivo.",
    cognitivePattern: "descoberta progressiva antes de agenda",
    topicShifts: ["capital da Austrália", "jogos de hoje"],
    implicitFollowUps: ["quanto?", "e hoje?", "que horas?", "tem outro?"],
    operationalQuestions: ["vocês cortam cabelo feminino?", "quanto custa?", "tem horário hoje?"],
    generalQuestions: ["que dia é hoje?", "qual jogo tem hoje?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "barber-female-curly",
    title: "Barbearia: cabelo feminino cacheado",
    domain: "barbearia",
    businessVertical: "appointment",
    persona: "Usuária objetiva, alterna entre estilo e pergunta operacional.",
    initialGoal: "Entender cortes para cabelo feminino cacheado e se o local atende.",
    cognitivePattern: "question satisfaction em pergunta sim/não operacional",
    topicShifts: ["Netflix", "clima"],
    implicitFollowUps: ["que horas?", "e preço?", "esse mesmo"],
    operationalQuestions: ["vocês cortam cabelo de mulher?", "tem profissional para cacheado?"],
    generalQuestions: ["qual filme mais assistido da Netflix agora?"],
    ambiguousQuestions: ["fica bom?"],
  },
  {
    id: "aesthetic-skin",
    title: "Estética: pele sensível",
    domain: "estetica",
    businessVertical: "appointment",
    persona: "Pessoa cautelosa, medo de reação na pele.",
    initialGoal: "Descobrir qual procedimento estético faz sentido para pele sensível.",
    cognitivePattern: "risco e restrição antes de recomendação",
    topicShifts: ["notícias de saúde", "previsão do tempo"],
    implicitFollowUps: ["e se irritar?", "quanto?", "tem hoje?"],
    operationalQuestions: ["faz limpeza de pele?", "qual valor?"],
    generalQuestions: ["vai chover hoje?", "tem notícia recente sobre protetor solar?"],
    ambiguousQuestions: ["é seguro?"],
  },
  {
    id: "restaurant-date",
    title: "Restaurante: jantar a dois",
    domain: "restaurante",
    businessVertical: "restaurant",
    persona: "Usuário quer impressionar sem parecer exagerado.",
    initialGoal: "Escolher mesa/prato para jantar a dois.",
    cognitivePattern: "intenção social antes de opção",
    topicShifts: ["futebol", "tecnologia"],
    implicitFollowUps: ["e vegetariano?", "que horas?", "tem outra mesa?"],
    operationalQuestions: ["tem reserva hoje?", "qual prato mais pedido?"],
    generalQuestions: ["qual jogo tem hoje?", "qual celular mais vendido?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "clinic-first-visit",
    title: "Consultório: primeira consulta",
    domain: "consultorio",
    businessVertical: "health",
    persona: "Paciente ansioso, quer saber como funciona sem expor demais.",
    initialGoal: "Entender se deve marcar primeira consulta.",
    cognitivePattern: "acolhimento sem diagnóstico",
    topicShifts: ["capital da Austrália", "notícias"],
    implicitFollowUps: ["quanto?", "precisa levar algo?", "e hoje?"],
    operationalQuestions: ["tem consulta hoje?", "aceita convênio?"],
    generalQuestions: ["quais notícias de saúde hoje?"],
    ambiguousQuestions: ["é grave?"],
  },
  {
    id: "store-shoe",
    title: "Loja: tênis para trabalho",
    domain: "loja",
    businessVertical: "commerce",
    persona: "Comprador pragmático, usa muito em pé.",
    initialGoal: "Escolher tênis confortável para trabalho.",
    cognitivePattern: "uso, restrição e orçamento antes de produto",
    topicShifts: ["clima", "futebol"],
    implicitFollowUps: ["e preto?", "tem meu número?", "qual você pegaria?"],
    operationalQuestions: ["tem estoque?", "qual preço?"],
    generalQuestions: ["vai chover hoje?", "quem joga hoje?"],
    ambiguousQuestions: ["dura bastante?"],
  },
  {
    id: "product-notebook",
    title: "Produto: compra de notebook",
    domain: "produto",
    businessVertical: "commerce",
    persona: "Profissional que usa navegador e planilhas e carrega o notebook.",
    initialGoal: "Comprar notebook até 5 mil.",
    cognitivePattern: "descobrir uso antes de recomendar modelo",
    topicShifts: ["capital da Austrália", "notícias de tecnologia"],
    implicitFollowUps: ["trabalho", "navegador e planilhas", "levo bastante"],
    operationalQuestions: ["tem esse modelo?", "qual preço?"],
    generalQuestions: ["qual celular mais vendido atualmente?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "sports-games",
    title: "Futebol: jogos e horários",
    domain: "futebol",
    businessVertical: "general",
    persona: "Torcedor casual, pergunta por jogos e escolhe um para assistir.",
    initialGoal: "Saber jogos de hoje, horários e opinião sobre qual assistir.",
    cognitivePattern: "follow-up implícito pelo tópico ativo",
    topicShifts: ["corte de cabelo", "clima"],
    implicitFollowUps: ["que horas?", "qual você assistiria?", "e amanhã?"],
    operationalQuestions: ["tem horário hoje para corte?"],
    generalQuestions: ["quais jogos tem hoje?", "quem ganhou ontem?"],
    ambiguousQuestions: ["vale ver?"],
  },
  {
    id: "weather-trip",
    title: "Clima: viagem curta",
    domain: "clima",
    businessVertical: "general",
    persona: "Pessoa planejando sair de casa, precisa decidir roupa e horário.",
    initialGoal: "Saber se vai chover e como se preparar.",
    cognitivePattern: "dado atual com ferramenta, sem chute",
    topicShifts: ["restaurante", "notebook"],
    implicitFollowUps: ["e de noite?", "preciso levar guarda-chuva?"],
    operationalQuestions: ["tem mesa coberta?"],
    generalQuestions: ["vai chover hoje em Ponta Grossa?", "qual a temperatura agora?"],
    ambiguousQuestions: ["dá para ir?"],
  },
  {
    id: "news-technology",
    title: "Notícia: tecnologia atual",
    domain: "noticia",
    businessVertical: "general",
    persona: "Usuário curioso, quer assunto recente mas não sabe o recorte.",
    initialGoal: "Entender notícias atuais de tecnologia.",
    cognitivePattern: "incerteza temporal e pergunta de recorte",
    topicShifts: ["agenda de corte", "perfume"],
    implicitFollowUps: ["me explica melhor", "e IA?", "qual importa mais?"],
    operationalQuestions: ["tem horário hoje?"],
    generalQuestions: ["quais notícias de tecnologia agora?", "qual celular vende mais?"],
    ambiguousQuestions: ["isso muda algo?"],
  },
  {
    id: "tech-phone",
    title: "Tecnologia: celular mais vendido",
    domain: "tecnologia",
    businessVertical: "commerce",
    persona: "Comprador confundindo popularidade com melhor escolha.",
    initialGoal: "Comprar celular novo.",
    cognitivePattern: "responder nuance e redirecionar para critério de compra",
    topicShifts: ["futebol", "barbearia"],
    implicitFollowUps: ["comprar", "câmera", "até 2 mil"],
    operationalQuestions: ["tem em estoque?", "faz entrega?"],
    generalQuestions: ["qual celular mais vendido atualmente?"],
    ambiguousQuestions: ["compensa?"],
  },
  {
    id: "relationship-boss",
    title: "Relacionamento: chefe distante",
    domain: "relacionamento",
    businessVertical: "general",
    persona: "Pessoa insegura no trabalho, buscando leitura emocional.",
    initialGoal: "Entender se o chefe não gosta dela.",
    cognitivePattern: "separar evidência de interpretação",
    topicShifts: ["notícias", "agenda"],
    implicitFollowUps: ["ele elogia os outros", "e se for comigo?", "o que eu faço?"],
    operationalQuestions: ["tem horário para amanhã?"],
    generalQuestions: ["tem alguma notícia sobre liderança?"],
    ambiguousQuestions: ["será?"],
  },
  {
    id: "finance-100k",
    title: "Finanças: 100 mil reais",
    domain: "financas",
    businessVertical: "general",
    persona: "Usuário com dinheiro parado, quer resposta direta mas precisa de critérios.",
    initialGoal: "Decidir o que fazer com 100 mil reais.",
    cognitivePattern: "horizonte e objetivo antes de recomendação",
    topicShifts: ["apartamento", "notícia econômica"],
    implicitFollowUps: ["não", "crescimento patrimonial", "e imóvel?"],
    operationalQuestions: ["qual consultoria atende hoje?"],
    generalQuestions: ["quais notícias de economia hoje?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "health-weight",
    title: "Saúde leve: acima do peso",
    domain: "saude_leve",
    businessVertical: "health",
    persona: "Pessoa querendo melhorar saúde e estética sem diagnóstico médico.",
    initialGoal: "Organizar próximos passos para perder gordura.",
    cognitivePattern: "rotina e desafio principal antes de plano",
    topicShifts: ["clima", "restaurante"],
    implicitFollowUps: ["ambos", "95 kg e 1,78", "alimentação"],
    operationalQuestions: ["tem consulta hoje?", "qual valor?"],
    generalQuestions: ["vai chover hoje?"],
    ambiguousQuestions: ["é muito ruim?"],
  },
  {
    id: "comparison-cars",
    title: "Comparação: Corolla ou Civic",
    domain: "comparacao_compra",
    businessVertical: "general",
    persona: "Comprador que quer escolher carro usado.",
    initialGoal: "Comparar Corolla e Civic sem critério definido.",
    cognitivePattern: "comparação baseada em perfis e ano",
    topicShifts: ["seguro", "clima"],
    implicitFollowUps: ["2019", "uso mais cidade", "qual você pegaria?"],
    operationalQuestions: ["tem financiamento?"],
    generalQuestions: ["vai chover no fim de semana?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "topic-shift-capital",
    title: "Mudança de assunto: corte para capital",
    domain: "mudanca_assunto",
    businessVertical: "appointment",
    persona: "Usuário muda de assunto sem avisar e volta depois.",
    initialGoal: "Marcar corte no sábado, pausa para curiosidade.",
    cognitivePattern: "pausar assunto, responder geral e retomar ponto exato",
    topicShifts: ["capital da Austrália", "futebol"],
    implicitFollowUps: ["interessante", "verdade", "e o horário?"],
    operationalQuestions: ["tem sábado?", "qual horário?"],
    generalQuestions: ["qual é a capital da Austrália?"],
    ambiguousQuestions: ["e aí?"],
  },
  {
    id: "topic-return-restaurant",
    title: "Retomada: restaurante depois de tecnologia",
    domain: "retomada_assunto",
    businessVertical: "restaurant",
    persona: "Usuário pesquisando restaurante e celular na mesma conversa.",
    initialGoal: "Reservar jantar, depois volta após pergunta tecnológica.",
    cognitivePattern: "retomada explícita de tópico pausado",
    topicShifts: ["celular mais vendido", "notícias"],
    implicitFollowUps: ["comprar", "voltando à reserva", "e o horário?"],
    operationalQuestions: ["tem mesa hoje?", "qual prato?"],
    generalQuestions: ["qual celular mais vendido atualmente?"],
    ambiguousQuestions: ["compensa?"],
  },
  {
    id: "perfume-work",
    title: "Produto: perfume para trabalho",
    domain: "produto",
    businessVertical: "commerce",
    persona: "Comprador quer perfume sem invadir ambiente fechado.",
    initialGoal: "Escolher perfume para trabalho.",
    cognitivePattern: "impressão desejada antes de nomes",
    topicShifts: ["agenda de corte", "clima"],
    implicitFollowUps: ["trabalho", "não faço ideia", "algo discreto"],
    operationalQuestions: ["tem estoque?", "qual valor?"],
    generalQuestions: ["vai chover hoje?"],
    ambiguousQuestions: ["é bom?"],
  },
  {
    id: "restaurant-allergy",
    title: "Restaurante: alergia e prato",
    domain: "restaurante",
    businessVertical: "restaurant",
    persona: "Cliente com restrição alimentar, precisa evitar risco.",
    initialGoal: "Escolher prato sem amendoim.",
    cognitivePattern: "segurança operacional antes de recomendação",
    topicShifts: ["notícia", "futebol"],
    implicitFollowUps: ["e sobremesa?", "tem certeza?", "quanto?"],
    operationalQuestions: ["tem amendoim?", "a cozinha separa?"],
    generalQuestions: ["qual jogo tem hoje?"],
    ambiguousQuestions: ["é seguro?"],
  },
  {
    id: "clinic-anxiety",
    title: "Consultório: ansiedade leve",
    domain: "consultorio",
    businessVertical: "health",
    persona: "Usuário ansioso procurando orientação inicial.",
    initialGoal: "Entender se deve buscar atendimento.",
    cognitivePattern: "acolher e orientar sem diagnosticar",
    topicShifts: ["tempo", "notícias"],
    implicitFollowUps: ["faz dias", "durmo mal", "e consulta?"],
    operationalQuestions: ["tem consulta essa semana?", "qual preço?"],
    generalQuestions: ["que dia é hoje?"],
    ambiguousQuestions: ["é normal?"],
  },
  {
    id: "store-gift",
    title: "Loja: presente ambíguo",
    domain: "loja",
    businessVertical: "commerce",
    persona: "Pessoa comprando presente sem conhecer muito o gosto.",
    initialGoal: "Escolher presente até 200 reais.",
    cognitivePattern: "destinatário, ocasião e risco antes de produto",
    topicShifts: ["clima", "notícia"],
    implicitFollowUps: ["pra minha mãe", "até 200", "algo útil"],
    operationalQuestions: ["tem embalagem?", "entrega hoje?"],
    generalQuestions: ["vai chover?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "aesthetic-hair-removal",
    title: "Estética: depilação primeira vez",
    domain: "estetica",
    businessVertical: "appointment",
    persona: "Cliente com vergonha e dúvida sobre dor.",
    initialGoal: "Entender depilação para primeira vez.",
    cognitivePattern: "acolhimento e expectativa realista",
    topicShifts: ["futebol", "Netflix"],
    implicitFollowUps: ["dói?", "quanto?", "tem hoje?"],
    operationalQuestions: ["faz depilação?", "qual profissional?"],
    generalQuestions: ["qual filme mais assistido agora?"],
    ambiguousQuestions: ["é tranquilo?"],
  },
  {
    id: "finance-apartment",
    title: "Finanças: comprar apartamento",
    domain: "financas",
    businessVertical: "general",
    persona: "Pessoa perguntando se vale a pena comprar apartamento.",
    initialGoal: "Comparar morar vs investir.",
    cognitivePattern: "ambiguidade, finalidade e horizonte",
    topicShifts: ["clima", "restaurante"],
    implicitFollowUps: ["morar", "financiar", "e aluguel?"],
    operationalQuestions: ["tem consultor hoje?"],
    generalQuestions: ["notícias de juros hoje"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "tech-laptop-programming",
    title: "Tecnologia: notebook para programação",
    domain: "tecnologia",
    businessVertical: "commerce",
    persona: "Estudante começando programação.",
    initialGoal: "Comprar notebook para programar.",
    cognitivePattern: "nível, ferramentas e orçamento antes de modelo",
    topicShifts: ["capital", "agenda"],
    implicitFollowUps: ["iniciante", "até 4 mil", "levo pra faculdade"],
    operationalQuestions: ["tem em estoque?", "parcela?"],
    generalQuestions: ["capital da Austrália?"],
    ambiguousQuestions: ["serve?"],
  },
  {
    id: "relationship-date",
    title: "Relacionamento: mensagem não respondida",
    domain: "relacionamento",
    businessVertical: "general",
    persona: "Pessoa ansiosa interpretando silêncio.",
    initialGoal: "Entender se deve mandar nova mensagem.",
    cognitivePattern: "separar fatos, hipóteses e próximo passo leve",
    topicShifts: ["futebol", "clima"],
    implicitFollowUps: ["faz 2 dias", "a gente saiu uma vez", "mando algo?"],
    operationalQuestions: ["tem horário no salão hoje?"],
    generalQuestions: ["qual jogo tem hoje?"],
    ambiguousQuestions: ["será que acabou?"],
  },
  {
    id: "health-food-routine",
    title: "Saúde leve: alimentação fora do plano",
    domain: "saude_leve",
    businessVertical: "health",
    persona: "Pessoa sabe o problema mas não sabe onde ajustar.",
    initialGoal: "Identificar momento crítico da alimentação.",
    cognitivePattern: "momento do dia antes de conselho",
    topicShifts: ["restaurante", "notícia"],
    implicitFollowUps: ["à noite", "peço delivery", "e fim de semana?"],
    operationalQuestions: ["tem nutricionista hoje?"],
    generalQuestions: ["notícia sobre ultraprocessados"],
    ambiguousQuestions: ["faz mal?"],
  },
  {
    id: "comparison-phone",
    title: "Comparação: iPhone ou Samsung",
    domain: "comparacao_compra",
    businessVertical: "commerce",
    persona: "Comprador compara marcas, precisa entender prioridade.",
    initialGoal: "Escolher celular entre iPhone e Samsung.",
    cognitivePattern: "ecossistema, câmera, bateria e orçamento",
    topicShifts: ["barbearia", "clima"],
    implicitFollowUps: ["câmera", "até 3500", "qual você pegaria?"],
    operationalQuestions: ["tem estoque?", "qual preço?"],
    generalQuestions: ["vai chover hoje?"],
    ambiguousQuestions: ["compensa?"],
  },
  {
    id: "barber-complaint",
    title: "Barbearia: usuário critica IA",
    domain: "barbearia",
    businessVertical: "appointment",
    persona: "Usuário impaciente, corrige o assistente quando ele foge.",
    initialGoal: "Perguntar serviço e preço sem tolerar resposta errada.",
    cognitivePattern: "assumir falha e responder pergunta real",
    topicShifts: ["Netflix", "futebol"],
    implicitFollowUps: ["não foi isso", "responde direito", "eu perguntei se corta"],
    operationalQuestions: ["corta cabelo feminino?", "quanto custa?"],
    generalQuestions: ["qual filme mais assistido da Netflix?"],
    ambiguousQuestions: ["tem isso?"],
  },
  {
    id: "restaurant-group",
    title: "Restaurante: grupo grande",
    domain: "restaurante",
    businessVertical: "restaurant",
    persona: "Pessoa organizando aniversário com grupo grande.",
    initialGoal: "Reservar mesa para 12 pessoas.",
    cognitivePattern: "capacidade e restrições antes de confirmação",
    topicShifts: ["tecnologia", "notícia"],
    implicitFollowUps: ["12 pessoas", "tem criança", "e bolo?"],
    operationalQuestions: ["tem mesa para sábado?", "cobra reserva?"],
    generalQuestions: ["qual celular mais vendido?"],
    ambiguousQuestions: ["dá certo?"],
  },
  {
    id: "product-camera",
    title: "Produto: câmera para viagem",
    domain: "produto",
    businessVertical: "commerce",
    persona: "Viajante quer câmera mas talvez celular baste.",
    initialGoal: "Comprar câmera para viagem.",
    cognitivePattern: "necessidade real antes de compra",
    topicShifts: ["clima do destino", "restaurante"],
    implicitFollowUps: ["só fotos de passeio", "não quero peso", "até 3 mil"],
    operationalQuestions: ["tem em estoque?", "aluga?"],
    generalQuestions: ["vai chover em Curitiba?"],
    ambiguousQuestions: ["vale a pena?"],
  },
  {
    id: "consultorio-price",
    title: "Consultório: preço e disponibilidade",
    domain: "consultorio",
    businessVertical: "health",
    persona: "Paciente direto, pergunta preço e agenda cedo.",
    initialGoal: "Saber valor e horário sem inventar disponibilidade.",
    cognitivePattern: "incerteza operacional fail-closed",
    topicShifts: ["capital", "clima"],
    implicitFollowUps: ["quanto?", "e hoje?", "mais cedo?"],
    operationalQuestions: ["qual valor?", "tem horário hoje?"],
    generalQuestions: ["que dia é hoje?"],
    ambiguousQuestions: ["serve pra mim?"],
  },
  {
    id: "mixed-free-chat",
    title: "Conversa livre: zigue-zague humano",
    domain: "mudanca_assunto",
    businessVertical: "general",
    persona: "Usuário conversa como pessoa real: compra, clima, saúde e agenda no mesmo fluxo.",
    initialGoal: "Testar resistência a zigue-zague sem perder assunto.",
    cognitivePattern: "orquestração universal com tópicos pausados",
    topicShifts: ["notebook", "clima", "corte", "finanças", "futebol"],
    implicitFollowUps: ["trabalho", "que horas?", "voltando", "qual você escolheria?"],
    operationalQuestions: ["tem horário hoje?", "qual preço?"],
    generalQuestions: ["vai chover?", "quais jogos tem hoje?"],
    ambiguousQuestions: ["vale a pena?"],
  },
]

export function generateScenarioSeeds(limit = 30) {
  return SCENARIOS.slice(0, Math.max(1, Math.min(limit, SCENARIOS.length)))
}

export function allScenarioSeeds() {
  return [...SCENARIOS]
}
